### ISSUE TITLE
「->Sql()」變得無法使用？

### ISSUE THREAD

**Issue by linmasahiro** [recca0120/eloquent-dumper#1]
您好，感謝您的套件。

我在我分別兩個專案中使用您的套件。
不過其中一個比較早開始用，是用0.2.0版。
下列的代碼是可以正常執行
```
$query = $this->newModelQuery();
...do something...
log_debug($query->sql());
```

不過這次新建的專案裝的是0.2.2版，一樣的寫法會直接拋出下列例外訊息
```
Call to undefined method Illuminate\Database\Eloquent\Builder::sql() 
```

請問使用方法有改嗎？謝謝

※不好意思標題打成->Sql()了，是->sql()才對

**Comment by recca0120** [comment]
被我改為 toRawSql，目前都是暫定，等1.0出來才會確定
